"""add cascade delete to asset_assignments foreign keys

Revision ID: 2b91345ea306
Revises: 283e165cee93
Create Date: 2026-07-15 14:51:44.732885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b91345ea306'
down_revision: Union[str, Sequence[str], None] = '283e165cee93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('asset_assignments_user_id_fkey'), 'asset_assignments', type_='foreignkey')
    op.drop_constraint(op.f('asset_assignments_asset_id_fkey'), 'asset_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'asset_assignments', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'asset_assignments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset_assignments', type_='foreignkey')
    op.drop_constraint(None, 'asset_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('asset_assignments_asset_id_fkey'), 'asset_assignments', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key(op.f('asset_assignments_user_id_fkey'), 'asset_assignments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
