"""add duplicate_dismissals table

Revision ID: 338c1cb343bc
Revises: 4268c2c34a94
Create Date: 2026-07-17 15:22:04.689016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338c1cb343bc'
down_revision: Union[str, Sequence[str], None] = '4268c2c34a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_dismissals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_a', sa.Integer(), nullable=False),
    sa.Column('user_id_b', sa.Integer(), nullable=False),
    sa.Column('dismissed_by', sa.Integer(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dismissed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_a'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id_b'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id_a', 'user_id_b', name='uq_dismissed_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duplicate_dismissals')
    # ### end Alembic commands ###
