"""add cascade delete to invoices foreign key

Revision ID: 4268c2c34a94
Revises: 2b91345ea306
Create Date: 2026-07-15 15:02:54.229339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4268c2c34a94'
down_revision: Union[str, Sequence[str], None] = '2b91345ea306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoices_asset_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_asset_id_fkey'), 'invoices', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###
