"""add commodity_type, brand_name, model_name, serial_number to assets

Revision ID: f3a197050095
Revises: fb18e15166f9
Create Date: 2026-07-09 09:46:52.291748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a197050095'
down_revision: Union[str, Sequence[str], None] = 'fb18e15166f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('commodity_type', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('brand_name', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('model_name', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('serial_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_assets_commodity_type'), 'assets', ['commodity_type'], unique=False)
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=True)
    op.drop_column('assets', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_index(op.f('ix_assets_commodity_type'), table_name='assets')
    op.drop_column('assets', 'serial_number')
    op.drop_column('assets', 'model_name')
    op.drop_column('assets', 'brand_name')
    op.drop_column('assets', 'commodity_type')
    # ### end Alembic commands ###
